### ISSUE TITLE
this._authHash is not a function

### ISSUE THREAD

**Issue by ghost** [nodecg/obs-remote-js#3]
I get this error every time I use obs.connect. Do I need nodecg or does this work on it's own?

`C:\Users\Max\Documents\stream launcher\node_modules\obs-remote\dist\obs-remote.js:168
        this._authHash(password, function(authResp) {
             ^

TypeError: this._authHash is not a function
    at OBSRemote.authenticate (C:\Users\Max\Documents\stream launcher\node_modules\obs-remote\dist\obs-remote.js:168:14)
    at C:\Users\Max\Documents\stream launcher\node_modules\obs-remote\dist\obs-remote.js:142:22
    at cb (C:\Users\Max\Documents\stream launcher\node_modules\obs-remote\dist\obs-remote.js:232:13)
    at OBSRemote._messageReceived (C:\Users\Max\Documents\stream launcher\node_modules\obs-remote\dist\obs-remote.js:593:13)
    at WebSocket._socket.onmessage (C:\Users\Max\Documents\stream launcher\node_modules\obs-remote\dist\obs-remote.js:157:18)
    at WebSocket.onMessage (C:\Users\Max\Documents\stream launcher\node_modules\ws\lib\WebSocket.js:418:14)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (C:\Users\Max\Documents\stream launcher\node_modules\ws\lib\WebSocket.js:816:10)
    at C:\Users\Max\Documents\stream launcher\node_modules\ws\lib\Receiver.js:477:18`

**Comment by SamuelGaona** [comment]
+1
